{
 "title": "OEE_bootcamp_DSS",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "Select Site",
    "query": "oslo,hannover,nuremberg,marseille,houston,sao_paulo,kuala_lumpur,chicago,rotterdam,london"
   },
   {
    "name": "production_line",
    "label": "Production Line",
    "query": {
     "query": "assets{parentExternalIds=['${site}_production']}"
    }
   },
   {
    "name": "machine",
    "label": "Machine",
    "query": {
     "query": "assets{parentIds=[$production_line]}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "OEE for $production_line",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "none",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "avg(ts{metadata={type='oee'},assetSubtreeIds=[{id=$production_line}]})",
     "relationshipsQuery": {
      "dataSetIds": [],
      "isActiveAtTime": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "wellQuery.items",
      "datapointsPath": "pressure.datapoints",
      "graphQlQuery": "\nquery {\n  wellQuery {\n    items {\n      name,\n      pressure {\n        datapoints(start: $__from, end: $__to, limit: 50) {\n          timestamp,\n          value\n        }\n      }\n    }\n  }\n}",
      "groupBy": "name"
     }
    }
   ]
  },
  {
   "title": "OEE History for $machine",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "aggregation": "none",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "isActiveAtTime": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000
      },
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "avg(ts{metadata={type='oee'},assetSubtreeIds=[{id=$production_line}]})",
     "label": "Production line average",
     "relationshipsQuery": {
      "dataSetIds": [],
      "isActiveAtTime": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "wellQuery.items",
      "datapointsPath": "pressure.datapoints",
      "graphQlQuery": "\nquery {\n  wellQuery {\n    items {\n      name,\n      pressure {\n        datapoints(start: $__from, end: $__to, limit: 50) {\n          timestamp,\n          value\n        }\n      }\n    }\n  }\n}",
      "groupBy": "name"
     }
    },
    {
     "aggregation": "none",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "ts{metadata={type='oee'},assetSubtreeIds=[{id=$machine}]}",
     "relationshipsQuery": {
      "dataSetIds": [],
      "isActiveAtTime": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "wellQuery.items",
      "datapointsPath": "pressure.datapoints",
      "graphQlQuery": "\nquery {\n  wellQuery {\n    items {\n      name,\n      pressure {\n        datapoints(start: $__from, end: $__to, limit: 50) {\n          timestamp,\n          value\n        }\n      }\n    }\n  }\n}",
      "groupBy": "name"
     }
    }
   ]
  },
  {
   "title": "Availability of $production_line",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "none",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "isActiveAtTime": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000
      },
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "avg(ts{metadata={type='availability'},assetSubtreeIds=[{id=$production_line}]})",
     "relationshipsQuery": {
      "dataSetIds": [],
      "isActiveAtTime": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "wellQuery.items",
      "datapointsPath": "pressure.datapoints",
      "graphQlQuery": "\nquery {\n  wellQuery {\n    items {\n      name,\n      pressure {\n        datapoints(start: $__from, end: $__to, limit: 50) {\n          timestamp,\n          value\n        }\n      }\n    }\n  }\n}",
      "groupBy": "name"
     }
    }
   ]
  },
  {
   "title": "Availability History for $machine",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregation": "none",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "avg(ts{metadata={type='availability'},assetSubtreeIds=[{id=$production_line}]})",
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "label": "Production line average",
     "relationshipsQuery": {
      "dataSetIds": [],
      "isActiveAtTime": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "wellQuery.items",
      "datapointsPath": "pressure.datapoints",
      "graphQlQuery": "\nquery {\n  wellQuery {\n    items {\n      name,\n      pressure {\n        datapoints(start: $__from, end: $__to, limit: 50) {\n          timestamp,\n          value\n        }\n      }\n    }\n  }\n}",
      "groupBy": "name"
     }
    },
    {
     "aggregation": "none",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "ts{metadata={type='availability'},assetSubtreeIds=[{id=$machine}]}",
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "relationshipsQuery": {
      "dataSetIds": [],
      "isActiveAtTime": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "wellQuery.items",
      "datapointsPath": "pressure.datapoints",
      "graphQlQuery": "\nquery {\n  wellQuery {\n    items {\n      name,\n      pressure {\n        datapoints(start: $__from, end: $__to, limit: 50) {\n          timestamp,\n          value\n        }\n      }\n    }\n  }\n}",
      "groupBy": "name"
     }
    },
    {
     "aggregation": "stepInterpolation",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "isActiveAtTime": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000
      },
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "ts{metadata={type='status'},assetSubtreeIds=[{id=$machine}]}",
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "relationshipsQuery": {
      "dataSetIds": [],
      "isActiveAtTime": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "wellQuery.items",
      "datapointsPath": "pressure.datapoints",
      "graphQlQuery": "\nquery {\n  wellQuery {\n    items {\n      name,\n      pressure {\n        datapoints(start: $__from, end: $__to, limit: 50) {\n          timestamp,\n          value\n        }\n      }\n    }\n  }\n}",
      "groupBy": "name"
     }
    },
    {
     "aggregation": "stepInterpolation",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "isActiveAtTime": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000
      },
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "ts{metadata={type='planned_status'},assetSubtreeIds=[{id=$machine}]}",
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "relationshipsQuery": {
      "dataSetIds": [],
      "isActiveAtTime": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "wellQuery.items",
      "datapointsPath": "pressure.datapoints",
      "graphQlQuery": "\nquery {\n  wellQuery {\n    items {\n      name,\n      pressure {\n        datapoints(start: $__from, end: $__to, limit: 50) {\n          timestamp,\n          value\n        }\n      }\n    }\n  }\n}",
      "groupBy": "name"
     }
    }
   ]
  },
  {
   "title": "Quality KPI of $production_line",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "none",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "isActiveAtTime": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000
      },
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "avg(ts{metadata={type='quality'},assetSubtreeIds=[{id=$production_line}]})",
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "relationshipsQuery": {
      "dataSetIds": [],
      "isActiveAtTime": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "wellQuery.items",
      "datapointsPath": "pressure.datapoints",
      "graphQlQuery": "\nquery {\n  wellQuery {\n    items {\n      name,\n      pressure {\n        datapoints(start: $__from, end: $__to, limit: 50) {\n          timestamp,\n          value\n        }\n      }\n    }\n  }\n}",
      "groupBy": "name"
     }
    }
   ]
  },
  {
   "title": "Quality History for $production_line",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 10 },
   "targets": [
    {
     "aggregation": "none",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "avg(ts{metadata={type='quality'},assetSubtreeIds=[{id=$production_line}]})",
     "label": "Production line average",
     "relationshipsQuery": {
      "dataSetIds": [],
      "isActiveAtTime": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "wellQuery.items",
      "datapointsPath": "pressure.datapoints",
      "graphQlQuery": "\nquery {\n  wellQuery {\n    items {\n      name,\n      pressure {\n        datapoints(start: $__from, end: $__to, limit: 50) {\n          timestamp,\n          value\n        }\n      }\n    }\n  }\n}",
      "groupBy": "name"
     }
    },
    {
     "aggregation": "none",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "ts{metadata={type='quality'},assetSubtreeIds=[{id=$machine}]}",
     "relationshipsQuery": {
      "dataSetIds": [],
      "isActiveAtTime": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "wellQuery.items",
      "datapointsPath": "pressure.datapoints",
      "graphQlQuery": "\nquery {\n  wellQuery {\n    items {\n      name,\n      pressure {\n        datapoints(start: $__from, end: $__to, limit: 50) {\n          timestamp,\n          value\n        }\n      }\n    }\n  }\n}",
      "groupBy": "name"
     }
    },
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "ts{metadata={type='count'},assetSubtreeIds=[{id=$machine}]}",
     "relationshipsQuery": {
      "dataSetIds": [],
      "isActiveAtTime": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "wellQuery.items",
      "datapointsPath": "pressure.datapoints",
      "graphQlQuery": "\nquery {\n  wellQuery {\n    items {\n      name,\n      pressure {\n        datapoints(start: $__from, end: $__to, limit: 50) {\n          timestamp,\n          value\n        }\n      }\n    }\n  }\n}",
      "groupBy": "name"
     }
    },
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "ts{metadata={type='good'},assetSubtreeIds=[{id=$machine}]}",
     "relationshipsQuery": {
      "dataSetIds": [],
      "isActiveAtTime": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "wellQuery.items",
      "datapointsPath": "pressure.datapoints",
      "graphQlQuery": "\nquery {\n  wellQuery {\n    items {\n      name,\n      pressure {\n        datapoints(start: $__from, end: $__to, limit: 50) {\n          timestamp,\n          value\n        }\n      }\n    }\n  }\n}",
      "groupBy": "name"
     }
    }
   ]
  },
  {
   "title": "Performance of $production_line",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "none",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "isActiveAtTime": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000
      },
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "avg(ts{metadata={type='performance'},assetSubtreeIds=[{id=$production_line}]})",
     "relationshipsQuery": {
      "dataSetIds": [],
      "isActiveAtTime": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "wellQuery.items",
      "datapointsPath": "pressure.datapoints",
      "graphQlQuery": "\nquery {\n  wellQuery {\n    items {\n      name,\n      pressure {\n        datapoints(start: $__from, end: $__to, limit: 50) {\n          timestamp,\n          value\n        }\n      }\n    }\n  }\n}",
      "groupBy": "name"
     }
    }
   ]
  },
  {
   "title": "Performance History for $production_line",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 15 },
   "targets": [
    {
     "aggregation": "none",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "avg(ts{metadata={type='performance'},assetSubtreeIds=[{id=$production_line}]})",
     "label": "Production line average",
     "relationshipsQuery": {
      "dataSetIds": [],
      "isActiveAtTime": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "wellQuery.items",
      "datapointsPath": "pressure.datapoints",
      "graphQlQuery": "\nquery {\n  wellQuery {\n    items {\n      name,\n      pressure {\n        datapoints(start: $__from, end: $__to, limit: 50) {\n          timestamp,\n          value\n        }\n      }\n    }\n  }\n}",
      "groupBy": "name"
     }
    },
    {
     "aggregation": "none",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "ts{metadata={type='performance'},assetSubtreeIds=[{id=$machine}]}",
     "relationshipsQuery": {
      "dataSetIds": [],
      "isActiveAtTime": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "wellQuery.items",
      "datapointsPath": "pressure.datapoints",
      "graphQlQuery": "\nquery {\n  wellQuery {\n    items {\n      name,\n      pressure {\n        datapoints(start: $__from, end: $__to, limit: 50) {\n          timestamp,\n          value\n        }\n      }\n    }\n  }\n}",
      "groupBy": "name"
     }
    },
    {
     "aggregation": "none",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "ts{metadata={type='status'},assetSubtreeIds=[{id=$machine}]}",
     "relationshipsQuery": {
      "dataSetIds": [],
      "isActiveAtTime": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "wellQuery.items",
      "datapointsPath": "pressure.datapoints",
      "graphQlQuery": "\nquery {\n  wellQuery {\n    items {\n      name,\n      pressure {\n        datapoints(start: $__from, end: $__to, limit: 50) {\n          timestamp,\n          value\n        }\n      }\n    }\n  }\n}",
      "groupBy": "name"
     }
    }
   ]
  }
 ]
}